name: flutter_foundation_models_gen
description: "Code generator for Flutter Foundation Models"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.5.3

dependencies:
  flutter_foundation_models_annotations:
    path: ../flutter_foundation_models_annotations
  source_gen: ^1.5.0
  analyzer: ^6.7.0
  build: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^4.0.0
