name: flutter_foundation_models_annotations
description: Annotations for Flutter Foundation Models. Use @Generable and @Guide to define structured output schemas.
version: 0.1.1
repository: https://github.com/AlexStrNik/flutter_foundation_models

environment:
  sdk: ^3.5.3

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
