name: flutter_foundation_models_annotations
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
