name: flutter_foundation_models
publish_to: none
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_foundation_models_annotations:
    path: ../flutter_foundation_models_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.7.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterFoundationModelsPlugin
